# 分配角色给 frontend-group 前端组 和 backend-group 后端组
# 并具有适当的权限
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argo
data:
  policy.csv: |
    p, role:admin, applications, *, *, allow
    p, role:lx, applications, *, *, allow
    g, admin, role:admin
    g, lx, proj:frontend:lx
    g, lx, proj:backend:lx
# kubectl apply -f argocd-rbac-cm -n argo
