stages:
  - init
  - test
  - build
  - manifests
  - deploy
  - verify

variables:
  # 初始化相关配置:
  # 是否需要初始化web, 初始化的工作包含拉取和构建运行Web应用的镜像
  FRONTEND_INIT: "false"
  # 是否需要初始化argo, 初始化的工作包含创建argo的proj
  BACKEND_INIT: "false"

  # Runner相关配置:
  # 运行前端的runner tag
  FRONTEND_TAG: node
  # 运行后端的runner tag
  BACKEND_TAG: go
  # 运行Docker的runner tag
  DOCKER_TAG: docker:26.1.0-dind-alpine3.19

  # 前端项目相关配置:
  # 作者/组织
  PROJECT_PROJECT_AUTHORS: lisa
  # 前端端项目名称
  FRONTEN_PROJECT_NAME: frontend
  # 版本号, 例如v1.0.0, latest, 这里使用了git tag <VERSION> 作为版本号, CI_COMMIT_TAG是gitlab ci内置命令
  FRONTEN_VERSION: ${CI_COMMIT_TAG}

  # 后端项目相关配置:
  # 作者/组织
  BACKEND_PROJECT_AUTHORS: lisa
  # 服务端项目名称
  BACKEND_PROJECT_NAME: backend
  # 版本号, 例如v1.0.0, latest, 这里使用了git tag <VERSION> 作为版本号, CI_COMMIT_TAG是gitlab ci内置命令
  BACKEND_VERSION: ${CI_COMMIT_TAG}
  # HTTP端口
  PORT1: 30001
  # gRPC端口
  PORT2: 30002
  # 使用的镜像, 除了dockerhub之外的镜像都需要添加供应商前缀
  GO_IMAGE: golang:1.22.2-alpine3.19
  # 构建的目标平台架构
  ARCH: amd64
  # 是否使用CGO
  CGO_ENABLED: 0
  # alpine user id
  UID: 10001

  # Docker 相关配置:
  # 当使用dind服务时，你必须指示docker与服务内部启动的daemon对话。
  # 这个守护进程可以通a网络连接来使用，而不是默认的/var/run/docker套接字。
  # 如果你使用的是GitLab Runner 12.7或更早版本的Kubernetes执行器和Kubernetes 1.6或更早版本，由于
  # Kubernetes执行器的连接方式，该变量必须设置为tcp://localhost:2375
  DOCKER_HOST: "tcp://docker:2375"
  # 这指示Docker不要重新启动TLS。如果远程注册表不是HTTPS, 就填写
  DOCKER_TLS_CERTDIR: ""

cache:
  key: nginx-quic
  paths:
    - frontend/node_modules

# Docker登录模板
.docker_login_template:
  #  variables:
  #    FF_NETWORK_PER_BUILD: "true"
  # 建议与你注册Runner选择的Docker镜像一致
  image: ${DOCKER_TAG}
  services:
    # 建议与你注册Runner选择的Docker镜像一致
    - ${DOCKER_TAG}
  before_script:
    - echo "正在查看Docker 信息"
    - docker info
    - echo "正在登录到远程注册表"
    - docker login $REGISTER_ADDRESS -u $REGISTER_USERNAME -p $REGISTER_PASSWORD

# argocd登录模板
.argocd_login_template:
  before_script:
    - echo "正在登录Argocd服务器"
    - >
      argocd login ${ARGO_SERVER} 
      --username ${ARGO_USER} 
      --password ${ARGO_PASS}
      --insecure

#job_frontend_test:
#  stage: test
#  image: node:18-alpine
#  tags:
#    - ${FRONTEND_TAG}
#  before_script:
#    - cd frontend
#    - npm install -g pnpm
#    - rm -rf node_modules
#  script:
#    - pnpm i
#    - pnpm lint
#  after_script:
#    - |
#      if [ $? -ne 0 ]; then
#        echo "测试失败
#        exit 1
#      fi
#  only:
#    - main
#    - dev

#job_backend_test:
#  stage: test
#  image: golang:1.22.2-alpine3.19
#  tags:
#    - ${BACKEND_TAG}
#  before_script:
#    - cd backend
#  script:
#    - go test ./...
#  after_script:
#    - |
#      if [ $? -ne 0 ]; then
#        echo "测试失败
#        exit 1
#      fi
#  only:
#    - main

job_backend_build:
  stage: build
  extends:
    - .docker_login_template
  before_script:
    - |
      if [ -n "$TAG_VERSION" ]; then
        echo "Git Tag版本号为: $TAG_VERSION"
      else
        echo "没有设置Tag版本号, 默认设置为 dev"
        export TAG_VERSION="dev"
      fi
    - echo $TAG_VERSION
  script:
    - >
      docker build
      -t $BACKEND_PROJECT_AUTHORS/$BACKEND_PROJECT_NAME:$TAG_VERSION
      -f ${BACKEND_PROJECT_NAME}/Dockerfile ${BACKEND_PROJECT_NAME}
      --build-arg GO_IMAGE=${GO_IMAGE}
      --build-arg ARCH=${ARCH}
      --build-arg CGO_ENABLED=${CGO_ENABLED}
      --build-arg UID=${UID}
      --build-arg PORT1=${PORT1}
      --build-arg PORT2=${PORT2}
    - docker tag $BACKEND_PROJECT_AUTHORS/$BACKEND_PROJECT_NAME:$TAG_VERSION $REGISTER_ADDRESS/$BACKEND_PROJECT_AUTHORS/$BACKEND_PROJECT_NAME:$TAG_VERSION
    - docker push $REGISTER_ADDRESS/$BACKEND_PROJECT_AUTHORS/$BACKEND_PROJECT_NAME:$TAG_VERSION
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'

job_create_argo_proj:
  stage: init
  image: ccr.ccs.tencentyun.com/lisa/alpine:latest
  extends:
    - .argocd_login_template
  before_script:
    - sshpass -e scp -o stricthostkeychecking=no deploy/frontend/kubernetes/argocd/create-frontend-proj.yml ${s_user}@${s_host1}:/tmp/
    - sshpass -e scp -o stricthostkeychecking=no deploy/backend/kubernetes/argocd/create-backend-proj.yml ${s_user}@${s_host1}:/tmp/
  script:
    - sshpass -e ssh -o stricthostkeychecking=no ${s_user}@${s_host1} '
      argocd proj create -f /tmp/create-frontend-proj.yml;
      argocd proj create -f /tmp/create-backend-proj.yml;
      argocd proj list;
      '
  after_script:
    - sshpass -e ssh -o stricthostkeychecking=no ${s_user}@${s_host1} '
      rm -rf /tmp/create-frontend-proj.yml;
      rm -rf /tmp/create-backend-proj.yml
      '
  only:
    variables:
      - $BACKEND_INIT == "true"

job_manifests:
  stage: manifests
  image: ccr.ccs.tencentyun.com/lisa/alpine:git
  before_script:
    - which ssh-agent || apk update && apk add openssh-client
    - mkdir -p /root/.ssh
    - echo $SSH_PRIVATE_KEY > /root/.ssh/id_ed25519
    - chmod 600 /root/.ssh/id_ed25519
    - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts || true
    - chmod 644 ~/.ssh/known_hosts
    # run ssh-agent
    - eval $(ssh-agent -s)
    # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add /root/.ssh/id_ed25519
    # Git
    - git config --global user.email gitlab-ci@gmail.com
    - git config --global user.name gitlab-ci
    - git clone git@gitlab.com:lookeke/manifests.git
    - cd manifests
    - ls -latr
  script:
    - sed -i "s/image:.*/image:${TAG_VERSION}/g" full-stack-engineering/backend/deployment.yml
    - git add full-stack-engineering/backend/deployment.yml
    - git commit -am "Update Image"
    - git push
  only:
    - dev
    - main

job_deploy:
  stage: deploy
  image: ccr.ccs.tencentyun.com/lisa/alpine:latest
  extends:
    - .argocd_login_template
  before_script:
    - sshpass -e scp -o stricthostkeychecking=no deploy/frontend/kubernetes/argocd/create-frontend-app.yml ${s_user}@${s_host1}:/tmp/
    - sshpass -e scp -o stricthostkeychecking=no deploy/backend/kubernetes/argocd/create-backend-app.yml ${s_user}@${s_host1}:/tmp/
  script:
    - sshpass -e ssh -o stricthostkeychecking=no ${s_user}@${s_host1} '
      argocd app create -f /tmp/create-frontend-app.yml;
      argocd app create -f /tmp/create-backend-app.yml;
      argocd app list;
      '
  after_script:
    - sshpass -e ssh -o stricthostkeychecking=no ${s_user}@${s_host1} '
      rm -rf /tmp/application-frontend.yml;
      rm -rf /tmp/application-backend.yml
      '
  only:
    - main
    - dev

job_verify:
  stage: verify
  image: ccr.ccs.tencentyun.com/lisa/alpine
  before_script:
    - apk add curl
  script:
    - curl -L https://${s_host1}
    - curl -L http://${s_host1}:30001/helloworld/lisa
    - curl -L http://${s_host1}:30002/helloworld/lisa
  only:
    - main
    - dev
