# 部署清单
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ccr.ccs.tencentyun.com/lisa/backend:dev
          ports:
            - containerPort: 30001
            - containerPort: 30002

          volumeMounts:
            - name: config-volume
              mountPath: /data/conf
          command: [ "/app/backend", "-conf", "/data/conf" ]
      volumes:
        - name: config-volume
          hostPath:
            path: /path/to/configs
