# 服务清单
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 30001
      nodePort: 30001
    - protocol: TCP
      port: 30002
      targetPort: 30002
      nodePort: 30002
  type: LoadBalancer
