apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: frontend # 项目名称
  namespace: argo # 项目所在的命名空间，默认为argocd，可根据实际情况调整
spec:
  # 项目描述
  description: "This project is for managing frontend applications"

  # 允许应用部署到的命名空间列表
  destinations:
  - namespace: frontend
    server: https://192.168.2.160:6443 # 集群API地址，示例值需替换为实际地址

  # 源代码仓库配置
  sourceRepos:
  - https://gitlab.com/lookeke/full-stack-engineering.git # 允许使用的Git仓库地址，根据实际情况修改

  # 角色与成员
  roles:
    - name: admin # 角色名称
      policies:
      # 允许admin角色在frontend项目中对所有应用进行所有操作
      - p, proj:frontend:admin, applications, *, frontend/*, allow
      # 允许查看frontend命名空间相关的集群信息
      - p, proj:frontend:admin, clusters, get, frontend/*, allow

  # 可选：项目默认值
  # 这些默认值可以被应用级别的设置覆盖
  # clusterResourceWhitelist, namespaceResourceBlacklist等可以根据需要添加
