server:
  http:
    addr: 0.0.0.0:30001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:30002
    timeout: 1s

# 数据库
data:
  database:
    host: 192.168.2.102
    username: dbuser_dba
    password: DBUser.DBA
    dbname: meta
    port: 5432
    ssl_mode: disable
    time_zone: Asia/Shanghai

  redis:
    user: default
    pass: "msdnmm,."
    addr: 192.168.2.192:6379
    db: 0
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s

# 身份验证&鉴权
auth:
  jwt_key: hqFr%3ddt32DGlSTOI5cO6@TH#fFwYnP$S

# 服务注册&发现
consul:
  address: 192.168.2.181:8500
  schema: http
  health_check: false

# 链路追踪
jaeger:
  service_name: full-stack-engineering-backend-api
  grpc:
    endpoint: 192.168.2.191:4317
  http:
    endpoint: 192.168.2.191:4318
