server:
  http:
    addr: 0.0.0.0:30001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:30002
    timeout: 1s

# 数据库
data:
  database:
    host: 159.75.231.54
    username: root
    password: msdnmm
    dbname: postgres
    port: 5432
    ssl_mode: disable
    time_zone: Asia/Shanghai

  redis:
    user: default
    pass: "263393"
    addr: 159.75.231.54:6379
    db: 0
    dial_timeout: 1s
    read_timeout: 0.2s
    WriteTimeout: 0_2S

# 身份验证&鉴权
auth:
  jwt_key: hqFr%3ddt32DGlSTOI5cO6@TH#fFwYnP$S
  service_key: some_jwt_sign_key
  api_key: some_api_key

# 服务注册&发现
consul:
  address: 159.75.231.54:8500
  Schema: http
  health_check: false

# 可观测性
jaeger:
  service_name: full-stack-engineering-backend-api
  grpc:
    endpoint: 159.75.231.54:4317
  http:
    endpoint: 159.75.231.54:4318
